### ISSUE TITLE
Initial Implementation

### ISSUE THREAD

**Issue by koushik30027** [KSSC-ORG/WEP#2]

**Comment by koushik30027** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92148118/155828934-47c28ccb-35e2-498f-af8f-3ff6d06ce577.png">

**Comment by 2010030045-Chaitanya** [comment]
![image](https://user-images.githubusercontent.com/76841688/155828973-283cf244-6037-4920-8863-d06253343758.png)

**Comment by 2010030167** [comment]
![image](https://user-images.githubusercontent.com/95115248/155829028-229a648b-178d-45ff-86c8-b793bc886acc.png)

**Comment by SOUMITH30097** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92148130/155829069-84d36751-1476-46bb-afdd-49202446d0d4.png">
